### ISSUE TITLE
Сетка для выводов

### ISSUE THREAD

**Issue by AlexAbak** [KiCad-RUS/kicad-gost-library#3]
В соглашении для данной библиотеки указана сетка для выводов компонентов 50 mils. Однако сами компоненты крупнее аналогичных компонентов стандартной библиотеки у которой также сетка для выводов 50 mils.
Возможно имеет смысл выравнивать выводы по сетке 100 mils для более удобной работы с компонентами на схеме в связи с тем что сетка 50 mils для столь крупных компонентов мелка.

**Comment by eldarkg** [comment]
@AlexAbak 
50 mils - это минимально допустимая сетка. Т.е. все что кратны сетки допустимы.

**Comment by AlexAbak** [comment]
@eldarkg Сетка 100 mils кратна сетке 50 mils, однако при переключении редактора схем на неё выводы элементов не попадают в узлы сетки. Например УГО транзисторов.

**Comment by eldarkg** [comment]
@AlexAbak с сеткой 50 mils УГО получаются более близки к ГОСТ (device-gost: R_TRIM, SA_SPDT, EMI_FILTER и т.д.). Со 100 mils не получается.
